version: "3.9"
services:
  example-app:
    image: nginx
    labels:
      dns.domain: "app.yourdomain.com"
      dns.type: "A"
      dns.value: "192.168.1.100"
      dns.enable: "true"

  another-app:
    image: nginx
    labels:
      dns.domain: "disabled.yourdomain.com"
      dns.type: "A"
      dns.value: "192.168.1.101"
      dns.enable: "false"
